### ISSUE TITLE
No support for Moodle 3.4?

### ISSUE THREAD

**Issue by opitz** [moodleuulm/moodle-local_sandbox#5]
Here at QMUL we are currently using Moodle 3.4 and the sandbox plugin. Now in the latest version this plugin requires at least Moodle 3.5 - so we are stuck with the problem that we cannot switch quickly to a new Moodle version but want to keep a stable 3.4 version of the sandbox plugin as well.
May I suggest that you provide a "MOODLE_34_STABLE" branch of the plugin next to the more recent MASTER branch so that those still living slightly in the past are still supported?!

**Comment by Kathrin84** [comment]
Hello opitz,
thank you for your request.
If you have a look at Moodle's plugins repository you can see that there's a version suitable for Moodle 3.4:
https://moodle.org/plugins/pluginversions.php?plugin=local_sandbox
We recommend to always use these versions and not to clone this gitHub repository.
If you would like to clone this repo, you can work with our release tags to get the version you need.
I hope this helps.
Best, Kathrin

**Comment by abias** [comment]
Hi Matthias,

let me add some details:
* If you look at https://moodle.org/plugins/pluginversion.php?id=16989, v3.5-r1 did not change anything in the plugin. You are perfectly fine to still use v3.4-r4 now.
* If you want to get the plugin from Github instead from the Moodle plugin repo, just pick the https://github.com/moodleuulm/moodle-local_sandbox/releases/tag/v3.4-r4 tag.
* We have thought about introducing stable branches in Github in the past, but we have decided against it as we are only able to support the latest Moodle version anyway (see https://github.com/moodleuulm/moodle-local_sandbox/blob/master/README.md#moodle-release-support for details).

So, picking the tag from Github might be a small overhead for you, but adding stable branches is a bigger overhead for us.

Anyway, have fun with the plugin in London :)

Cheers,
Alex
